<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-8IGUF9C" name="anotacionestestng.SegundoSet" tests="8" failures="1" timestamp="2021-09-06T17:05:52 COT" time="0.028" errors="0">
  <testcase name="clicAlHomePage" time="0.002" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="clicAlCarrito" time="0.004" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="pruebaCuatro" time="0.002" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="clicAlUsuario" time="0.003" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="pruebaCinco" time="0.006" classname="anotacionestestng.SegundoSet">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at anotacionestestng.SegundoSet.pruebaCinco(SegundoSet.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pruebaCinco -->
  <system-out/>
  <testcase name="pruebaTres" time="0.003" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="clicAlCarrito" time="0.006" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
  <testcase name="clicAlCarrito" time="0.002" classname="anotacionestestng.SegundoSet"/>
  <system-out/>
</testsuite> <!-- anotacionestestng.SegundoSet -->
